---
title: "Project Description"
---

## Overview:

Testing push

The Boating and Angling Interview Trial (BAIT) is a survey that collects fishing and boating information from commercial and recreational boaters. This program is needed to collect important data that will help to:

1.  More accurately assess the fisheries and overall health of fish and invertebrate populations in the USVI. Specifically, this program will enable more accurate estimates of the total amount of fish caught and landed in the Territory (specifically mention stock assessments?).

2.  To gather information about boating activities which will allow local agencies to better manage boating facilities (marinas, boat ramps, moorings) and better promote recreational use of resources.

## Who Will Be Sampled:

All commercial and recreational boaters and fishers.

All interviews and information collected will be anonymous.

Participation is voluntary. However, gathering this fundamental data is imperative to ensuring safe, enjoyable, and sustainable boating and fishing in the USVI.

## When and Where:

DFW staff/personnel will conduct interviews on randomly selected days at randomly selected times and locations. Interviews will occur during weekdays, weekends, and holidays.
